/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BasDato;

import javax.swing.JOptionPane;

/**
 *
 * @author U1
 */
public class AnadirUser extends javax.swing.JFrame {
    private String contraseña;
    private String usuario;
    
    public AnadirUser() {
        initComponents();
        this.errorContraseña.setVisible(false);
        this.errorNombre.setVisible(false);
        txtBasesGuardadas.setEnabled(false);
        this.setLocationRelativeTo(null);
    }
    public boolean valContrasenia(String contr){
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        btAceptar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        errorNombre = new javax.swing.JLabel();
        errorContraseña = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        boxBases = new javax.swing.JComboBox<>();
        txtBasesGuardadas = new javax.swing.JTextField();
        btAgregarBase = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Añadir usuario");
        setResizable(false);

        jLabel1.setText("Crear usuario");

        jLabel2.setText("Nombre: ");

        jLabel3.setText("Contraseña: ");

        btAceptar.setText("Aceptar");

        btCancelar.setText("Cancelar");

        errorNombre.setForeground(new java.awt.Color(255, 0, 0));

        errorContraseña.setForeground(new java.awt.Color(255, 0, 0));

        jLabel4.setText("Bases de datos:");

        boxBases.setMaximumRowCount(20);
        boxBases.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "\"No hay bases registradas\"" }));

        btAgregarBase.setText("+");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorContraseña)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(errorNombre)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                        .addComponent(txtContraseña)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBasesGuardadas, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btCancelar)
                                        .addGap(155, 155, 155)
                                        .addComponent(btAceptar))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(boxBases, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btAgregarBase)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(errorNombre)
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(errorContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(boxBases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAgregarBase, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBasesGuardadas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAceptar)
                    .addComponent(btCancelar))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnadirUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnadirUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnadirUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnadirUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnadirUser().setVisible(true);
            }
        });
    }
    
    public boolean validaEspacios(){
        usuario = txtNombre.getText();
        contraseña = txtContraseña.getText();
        lowerCase(usuario, contraseña);
        boolean valida = true;
        if(txtNombre.getText().isEmpty()){
           errorNombre.setText("No puede haber espacios en blanco");
           errorNombre.setVisible(true);
           valida = false;
        }else{errorNombre.setVisible(false);}
        if(txtContraseña.getText().isEmpty()){
            errorContraseña.setText("No puede haber espacios en blanco");
            errorContraseña.setVisible(true);
            valida = false;
        }else{errorContraseña.setVisible(false);}
        if(txtNombre.getText().length()<7 || txtNombre.getText().length()>12){
            errorNombre.setText("El nombre debe ser mayor a 7 caracteres y menor a 12 caracteres");
            errorNombre.setVisible(true);
            valida = false;
        }else{errorNombre.setVisible(false);}
        if(txtContraseña.getText().length()<7 || txtContraseña.getText().length()>15){
            errorContraseña.setText("La contraseña debe ser mayor a 7 caracteres y menor a 15 caracteres");
            errorContraseña.setVisible(true);
            valida = false;
        }else{errorContraseña.setVisible(false);}
        if(!validaContraseña(contraseña)){
            JOptionPane.showMessageDialog(this, "La contraseña debe contener al menos un número,\n una letra y un carácter especial de\n" +
"los siguientes: ?, $, #, @, !");
            valida = false;
        }
        if(txtBasesGuardadas.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe agregar al menos una base");
            valida = false;
        }
        return valida;
    }
    private boolean validaContraseña(String contraseña){
        boolean valida = false;
        String[] lista = contraseña.split("");
        final String[] LETRAS = {"a","b","c","d","e","f","g","h","i","j","k","l","m","n","ñ","o"
                                ,"p","q","r","s","t","u","v","w","x","y","z"};
        final String[] ESPECIALES = {"?", "$", "#", "@", "!"};
        final String[] NUMEROS = {"0","1","2","3","4","5","6","7","8","9"};
        int cantNumeros = 0;
        int cantLetras = 0;
        int cantEspeciales = 0;
        for (int i = 0; i < lista.length; i++) {
            for (int j = 0; j < LETRAS.length; j++) {
                if(lista[i].equals(LETRAS[j])){
                    cantNumeros++;
                }
            }
            for(int j = 0;j<ESPECIALES.length; j++){
                if(lista[i].equals(ESPECIALES[j])){
                    cantEspeciales++;
                }
            }
            for (int j = 0; j < NUMEROS.length; j++) {
                if (lista[i].equals(NUMEROS[j])) {
                    cantLetras++;
                }
            } 
        }
        if(cantEspeciales>1 && cantLetras>1 && cantNumeros>1){
            valida = true;
        }
        return valida;
    }
    private void lowerCase(String pNombre, String pContraseña){
        this.usuario = pNombre.toLowerCase();
        this.contraseña = pContraseña.toLowerCase();
    }
    public void mostrarVentana(AnadirUser ventana){
        ventana.setVisible(true);
    }
    public void cerrarVentana(AnadirUser ventana){
        ventana.setVisible(false);
    }
    public void agregarTexto(String texto){
        txtBasesGuardadas.setText(txtBasesGuardadas.getText()+","+texto);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> boxBases;
    public javax.swing.JButton btAceptar;
    public javax.swing.JButton btAgregarBase;
    public javax.swing.JButton btCancelar;
    private javax.swing.JLabel errorContraseña;
    private javax.swing.JLabel errorNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JTextField txtBasesGuardadas;
    public javax.swing.JPasswordField txtContraseña;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
